# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niblr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niblr.Restaurant'),
            preserve_default=False,
        ),
    ]
