# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niblr', '0002_userrating_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_classification',
            field=models.CharField(choices=[('0', 'Cheap'), ('1', 'Mid-range'), ('2', 'Expensive')], default='1', max_length=12),
        ),
    ]
