# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niblr', '0003_auto_20170313_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('name', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set([('author', 'restaurant')]),
        ),
    ]
