# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niblr', '0004_auto_20170313_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='comments',
            field=models.TextField(help_text='Keep it under 140 chars', max_length=140),
        ),
    ]
