# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niblr', '0005_auto_20170313_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='minutes_walk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_classification',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
